# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  machine-executor:
    machine:
      # specify the version you desire here
      image: ubuntu-2004:202104-01

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout

      # Create Docker Network
      - run:
          name: Start selenium grid
          command: |
            docker-compose -f docker-compose-v3.yml up -d

      # run tests!
      - run:
          name: Execute tests!
          command: |
            ./gradlew test --tests "AppleTest.IPhone13ProMax256GoBleuAlpinTest"

      - run:
          name: Stop selenium grid
          command: |
            docker-compose -f docker-compose-v3.yml down